### ISSUE TITLE
Wildcard support for Asset Paths

### ISSUE THREAD

**Issue by AaronSadlerUK** [Mulliman/xStatic-for-Umbraco#1]
It would be useful to being able to input asset paths with a wildcard e.g. `/lib/*` when including assets so that they get added recursively 😁😁

**Comment by Mulliman** [comment]
[XStatic.WildcardDlls.zip](https://github.com/Mulliman/xStatic-for-Umbraco/files/6003059/XStatic.WildcardDlls.zip)

Do you want to drop the following dlls in your bin folder (backup the old xStatic ones first) and see if this matches the behaviour you expect?

I've tested it with some basic paths like "/assets/*" on a couple of sites and it seems to work for me.

If you're happy with it I'll make it into a new release and upload to our.umbraco.

**Comment by AaronSadlerUK** [comment]
Yep i can confirm that works as expected

**Comment by Mulliman** [comment]
This was included in release 1.0.0
