### ISSUE TITLE
xStatic export as html problem

### ISSUE THREAD

**Issue by SvenGoormans** [Mulliman/xStatic-for-Umbraco#10]
Hello!

I'm using xStatic v1.1.0 on umbraco v8.17.1.
All was working well until the 'export as html' stopped working.
All assets are being deployed correctly but there is no html.

Any idea why?
Thanks!

**Comment by SRandomName** [comment]
Important note - Export as json works and creates all pages in json format

**Comment by Mulliman** [comment]
If Json works and HTML doesn't this usually indicates that getting the page via a web client is failing. The json generator doesn't use a client of any kind.

It may be an SSL issue; try the web.config fix outlined in this troubleshooting page:

https://www.sammullins.co.uk/software/xstatic-for-umbraco/troubleshooting/

<appSettings>
    ...
    <add key="xStatic.TrustSsl" value="true" />
</appSettings>
