### ISSUE TITLE
SqliteException: SQLite Error 1: 'near "ALTER": syntax error'.

### ISSUE THREAD

**Issue by deanleigh** [Mulliman/xStatic-for-Umbraco#11]
Hey Sam,
finally got around to trying XStatic but in V10.
![Screenshot 2022-06-21 155411](https://user-images.githubusercontent.com/6745929/174830728-50485044-45c5-44f0-8274-52ff933cce59.png)
The error I have seems to be SQLite so wondered Is this supported yet?

**Comment by Mulliman** [comment]
@deanleigh Unfortunately I only ever got this working with SQL server.

**Comment by Mulliman** [comment]
This should now be fixed in v3 beta NuGet packages.
