### ISSUE TITLE
Linux environment not able to create directories in App_Data

### ISSUE THREAD

**Issue by adam-werner** [Mulliman/xStatic-for-Umbraco#17]
In testing the Build of a saved site, the writing of the site to the Umbraco environment fails.  The resulting error output with the CMS in debug = true follows:

> Received an error from the server
> An error occurred
> Could not find a part of the path '/home/site/wwwroot/App_Data/xStatic/output/1/index.html'.
> 
> Exception Details
> System.IO.DirectoryNotFoundException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Could not find a part of the path '/home/site/wwwroot/App_Data/xStatic/output/1/index.html'.

I've attached the [stacktrace.txt](https://github.com/Mulliman/xStatic-for-Umbraco/files/9766359/stacktrace.txt) from this error for additional review.

Interestingly enough, while troubleshooting to this point, if the directory structure is pre-seeded, an index.html file is saved but further directories cannot be constructed in that directory.

To confirm, the Build function works as expected in a Windows environment, it just appears that directories are not able to be constructed.

I would like to take this issue and work on a solution for your review.

Thank you.

**Comment by Mulliman** [comment]
This is now included in the 3.0.2 Beta NuGet package.

Thanks for all your work Adam
