### ISSUE TITLE
Fails when using with Azure block file provider

### ISSUE THREAD

**Issue by hifi-phil** [Mulliman/xStatic-for-Umbraco#2]
Thanks Sam, great package. Having some fun with images though!?!?

Tried to use it with the Azure blob file provider (https://our.umbraco.com/packages/collaboration/umbracofilesystemprovidersazure/) 

and it fails then deploying because it's trying to download the image from a local path which doesn't exist. 

I can help with a PR if you point me in the right direction.

Also RE NuGet, I've talked to Matt Wise and we'll be happy to help you set up GitHub actions to deploy directly to Nuget if you would like?

**Comment by Mulliman** [comment]
Hi Phil

You should probably be able to do this using custom code just for your instance, but it would also be cool to have blob storage support built in. You can give this a try:

1. Create a new generator

```
using System.Collections.Generic;
using System.Threading.Tasks;
using Umbraco.Web;
using XStatic.Generator.Storage;

namespace XStatic.Generator
{
    public class StaticSiteGeneratorWithBlobStorageImages : StaticHtmlSiteGenerator
    {
        public StaticSiteGeneratorWithBlobStorageImages(IUmbracoContextFactory umbracoContextFactory,
            IStaticSiteStorer storer,
            IImageCropNameGenerator imageCropNameGenerator)
            : base(umbracoContextFactory, storer, imageCropNameGenerator)
        {
        }

        public override Task<string> GenerateMedia(int id, int staticSiteId, IEnumerable<Crop> crops = null)
        {
            // Do your Blob stroage retrieval here.
            // Save it to the correct folder (you can use GeneratorBase.GenerateMedia as an example for this.)

            // you can fallback to the existing one if
            return base.GenerateMedia(id, staticSiteId, crops);
        }
    }
}
```

Then in the xStaticConfig.json file in App_Plugins add the reference to this new class in the existing HTML site or a new one if you'd rather.

```
{
      "id": "html",
      "name": "HTML site",
      "transformerFactory": "XStatic.Generator.Transformers.DefaultHtmlTransformerListFactory, XStatic.Generator",
      "generator": "XStatic.Generator.StaticSiteGeneratorWithBlobStorageImages, XStatic.Generator"
}
```

That should be all that is needed, but I haven't tried this so there may be some edge cases.

Have a go and let me know if you have any issues I can help with.

Ta
Sam

**Comment by Mulliman** [comment]
P.s. yes, NuGet would be cool. I'm currently building another pet project at the moment, but I will likely come back to NuGettifying xStatic and I will let you know if I need any help. Cheers.

**Comment by hifi-phil** [comment]
Hi Sam

Thanks for the in-depth answer, it really helped me get to a solution quickly. The only gotcha was I needed to add it to the IOC container using a composer before it would be picked up by the json config file. Once I realised that it was all plain sailing. 

In my generator, I didn't really need to connect to Azure Blob container or handle any of that messiness. Umbraco has a standardised file provider that abstracts all that.

```
_mediaFileSystem.OpenFile(partialPath);  //Umbraco.Core.IO.IMediaFileSystem
```

I think using this abstraction you could remove the parts of your generator and storer that retrieve the file, making it much simpler. It would also support blobs out of the box. xStatic wouldn't care where the file originate.

Let me know if you want me to take a look and create a PR.

**Comment by Mulliman** [comment]
I knew there'd be something simple like that!

If you do want to PR this in then I'll certainly accept it, this seems much nicer than the way I've done it!

Cheers

**Comment by hifi-phil** [comment]
OK cool, I'll take a look
