### ISSUE TITLE
Unable to resolve service for type 'XStatic.Core.Actions.IActionRepository' while attempting to activate 'XStatic.Controllers.ActionsController'.

### ISSUE THREAD

**Issue by pdao1** [Mulliman/xStatic-for-Umbraco#20]
Hi,

As soon as I click on the tab at the top, I receive this error:

Unable to resolve service for type 'XStatic.Core.Actions.IActionRepository' while attempting to activate 'XStatic.Controllers.ActionsController'.

Umbraco Version: 9.2
Dotnet Version: 5.0

Installed: xStatic/xStatic Netlify
Version: 2.0.3-beta

![image](https://user-images.githubusercontent.com/69880265/201507246-80b2c801-e4f6-468d-8fd7-c5f16c70a4b4.png)

**Comment by Mulliman** [comment]
Hey

Have you added `services.AddXStatic().Automatic().Build();` to your `ConfigureServices` method in `Startup.cs`?

It's part of the package install instructions on v3, but is less clear that it needs doing on v2.

**Comment by pdao1** [comment]
Hi Sam!

Thanks so much for getting back to me.  Just added it to my Startup.cs and the error is gone.. Appreciate it!!!!
Phung Dao
Project Coordinator
RVCM
 <http://rvcm.com/>		
	
***@***.*** ***@***.***>
	
808-600-8883

677 Ala Moana Blvd #820, Honolulu, HI 96813

rvcm.com <http://rvcm.com/>	
 <https://www.facebook.com/revacomm>		
 <https://www.linkedin.com/company/revacomm/>		
 <https://www.instagram.com/revacomm/?hl=en>		
 <https://twitter.com/revacomm>
