### ISSUE TITLE
Add client-side validation to the definition forms

### ISSUE THREAD

**Issue by adam-werner** [Mulliman/xStatic-for-Umbraco#22]
In the **Site Definition**, **Action Definition** and **Export Type Definition** forms, submissions without field entries can result in an error.

### Site Definition Form
![sc-xstatic-site-definition](https://user-images.githubusercontent.com/1880591/209225738-e06defc9-afa3-47ed-ab36-ee45735b3b99.png)
![sc-xstatic-site-definition-error](https://user-images.githubusercontent.com/1880591/209225751-422a860d-965a-467a-b9db-23c28951be9f.png)

### Action Definition Form
![sc-xstatic-action-definition](https://user-images.githubusercontent.com/1880591/209225806-24bcfa53-17f2-4078-9e1a-f620d8a584be.png)
![sc-xstatic-action-definition-error](https://user-images.githubusercontent.com/1880591/209225813-658287e7-8912-49f7-ad7f-9ceeda726f2e.png)

### Export Type Definition
![sc-xstatic-exporttype-definition](https://user-images.githubusercontent.com/1880591/209225853-96976be1-33a8-48cc-8d43-1b3afaed1b45.png)
![sc-xstatic-exporttype-definition-error](https://user-images.githubusercontent.com/1880591/209225866-216db1e2-1d61-4ed9-a939-cc08c260d9d9.png)

### Possible solution approach
With some angularjs controller updates, form validation can be incorporated there.  Alternatively, the corresponding API endpoints being called by the angularjs controllers can return validation messaging errors.

**Comment by Mulliman** [comment]
xStatic 14 now has much better validation with the UUI refactor.
