### ISSUE TITLE
Could not load type 'SqlGuidCaster', Umbraco 13.4.0

### ISSUE THREAD

**Issue by sebastiandammark** [Mulliman/xStatic-for-Umbraco#29]
When trying to install on an Umbraco 13.4.0 I get the following error when accessing the dashboard:

`Unable to load one or more of the requested types. Could not load type 'SqlGuidCaster' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.`

I've attached the full stacktrace here.
And I've also added the Program.cs as a .txt file.

[xstatic_details.txt](https://github.com/user-attachments/files/16097854/xstatic_details.txt)
[Program.txt](https://github.com/user-attachments/files/16097864/Program.txt)

**Comment by Mulliman** [comment]
Hi Thanks for the details.

I have been able to replicate this locally, so will see if I can find a fix.

**Comment by Mulliman** [comment]
I've been able to fix this by adding the following package reference.

`<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />`

I will look to release a v13 version of xStatic soon with this included.

**Comment by Mulliman** [comment]
This should now be fixed in v13.0.1.

Just note that I think the base reference is for Umbraco 13.4.1

**Comment by Mulliman** [comment]
If you don't want to upgrade to latest then the package reference noted above should do the trick.
