### ISSUE TITLE
Netlify doesn't appear after installation

### ISSUE THREAD

**Issue by sebastiandammark** [Mulliman/xStatic-for-Umbraco#31]
As you can see, I've installed the xStatic.Netlify package on my umbraco installation, but for some reason it looks like that it never gets picked up 🤷‍♂️ 

Shows that the package is installed in the project
![image](https://github.com/user-attachments/assets/7ebb81dc-f676-474f-9f3c-dcda22becc8a)

The Deployment Target dropdown is empty
![image](https://github.com/user-attachments/assets/50018a8b-a8d8-43a1-977e-ceb992a600e7)

The umbraco solution doesn't reflect that the Netlify extension should be installed
![image](https://github.com/user-attachments/assets/2ca54f96-91ca-4ec3-a3cd-4f332e2d99f3)

**Comment by Mulliman** [comment]
Hi

I think I've seen this when the compiler decides to not include unused assemblies.

Easiest way to get over this is to add the following to program.cs:

```
using XStatic.Netlify;

...

builder.Services.AddNetlifyActions();
```

You may end up using the Netlify 404 action anyway, so you may as well put it in.

I'll update the docs / readme in v14 to make this clear.

Best of luck
Sam

**Comment by sebastiandammark** [comment]
Yeah, that did the trick 👍 
Thanks.

// Sebastian
