### ISSUE TITLE
Upgrading xStatic deletes user config

### ISSUE THREAD

**Issue by hifi-phil** [Mulliman/xStatic-for-Umbraco#4]
Hi Sam

Just upgraded to 1.1 and the process wiped out my local config. Might be better to move the config file to the config directory in Umbraco?

Phil

**Comment by Mulliman** [comment]
Ok, Phil. Good idea.

I was thinking of changing it a bit when I refactored for Umbraco .net core, but it sounds like this may be worth doing earlier rather than later.

Cheers

**Comment by hifi-phil** [comment]
Thanks Sam, think about creating a new IStaticSiteStorer as well to push the build to an Azure container. It will work well in CI/CD swapped environments and is also previewable.

Should be easy to add to the config in a similar way to your transformers and generators?
