### ISSUE TITLE
User permissions on dashboard

### ISSUE THREAD

**Issue by hifi-phil** [Mulliman/xStatic-for-Umbraco#6]
When adding the user group xStatic to the Editor role the section link is available but the dashboard doesn't display so they can't upload sites. Strangely they can edit generated site settings.

**Comment by Mulliman** [comment]
Hey Phil

I've finally got round to having a look at this.

This is quite a simple fix, you can add any roles you want to have access to the dashboard in the file "\App_Plugins\xStatic\package.manifest"

```
"dashboards": [
    {
      "alias": "MainDashboard",
      "view": "/App_Plugins/xStatic/dashboards/MainDashboard.html",
      "sections": [ "xstatic" ],
      "access": [
        { "deny": "translator" },
        { "grant": "admin,editor" }
      ]
    }
```
See how I've added editor to the grant line.

I don't think I'm going to change this by default; I think for editors it should use the auto publish functionality for simplicity, or the site admin should decide that the dashboard should be made available. It's an easy thing to add in if required.
