### ISSUE TITLE
Language variants

### ISSUE THREAD

**Issue by steve-crook** [Mulliman/xStatic-for-Umbraco#9]
I've noticed that when I build my HTML site, none of the language variants are generated and only the default language is available. Could export of these translated pages be added?

**Comment by Mulliman** [comment]
Yes this could be done, but there are more than one potential ways to achieve it so it wasn't added in as a default option.

It comes down to whether different languages should be exported to different locations or whether they should be all deployed to the same location.

Deploying each language to separate subdomain should be pretty simple, but would need a new field in the dashboard to allow the user to select the language to export.

Deploying all the languages to the same location would require some link transformation and dropping files in folders that may not match the CMS structure. Again possible, but not added in by default. This could probably be achieved on an individual basis by inheriting from StaticHtmlSiteGenerator and overriding the GeneratePage method to create and store files for each language version of the node. Based on how these language versions are stored a new Transformer (and TransformerListFactory) may need to be created to ensure that links point to correct locations.

If one approach is clearly better, then maybe it could be added as base functionality, but at present it is only built for a single language.

**Comment by BaneBanissimo** [comment]
My setup was as follows:
- A content tree with languages in subfolders, so at the end default language: "/index.html", additional language: "/en/index.html".

So all en variants had to be created simply in the same structure again under the folder "/en".

I actually only had to overwrite the StaticHtmlSiteGenerator and extend the GeneratePage method a bit:

```
public override async Task<GenerateItemResult> GeneratePage(int id, int staticSiteId, IFileNameGenerator fileNamer, IEnumerable<ITransformer> transformers = null)
{
    List<string> generatedFilesHandled = new List<string>();

    SslTruster.TrustSslIfAppSettingConfigured();

    var node = GetNode(id);

    if (node == null)
    {
        return null;
    }
    if (node.TemplateId == null)
    {
        return null;
    }

    try
    {
        string generatedFileLocation = "";

        foreach (var culture in node.Cultures)
        {
            var url = node.Url(_publishedUrlProvider, mode: UrlMode.Relative, culture: culture.Key);
            string absoluteUrl = node.Url(_publishedUrlProvider, mode: UrlMode.Absolute, culture: culture.Key);

            var fileData = await GetFileDataFromWebClient(absoluteUrl);

            var transformedData = RunTransformers(fileData, transformers);

            var filePath = fileNamer.GetFilePartialPath(url);

            generatedFileLocation += await Store(staticSiteId, filePath, transformedData);
        }

        return GenerateItemResult.Success("Page", node.UrlSegment, generatedFileLocation);
    }
    catch (Exception e)
    {
        return GenerateItemResult.Error("Page", node.UrlSegment, e.Message);
    }
}
```

I added the foreach loop and the culture to the node.Url calls.

**Comment by Mulliman** [comment]
Thanks for adding this, it's a great reference for others.

**Comment by Mulliman** [comment]
Language variants have now been added to the v14 version.
